# -*- coding: utf-8 -*-
"""Multi-Agent AI for Scientific Literature Intelligence .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XhopJxB-GZp8yeHdxFBApaa3eHNpDMJr
"""

!pip install --upgrade pip
!pip install numpy==1.26.4
!pip install crewai==0.28.8 crewai_tools==0.1.6 langchain_groq==0.1.5 arxiv

import os

# Groq API Key (REQUIRED)
os.environ["GROQ_API_KEY"] = " "

# Serper API Key (REQUIRED since you want to use Serper)
os.environ["SERPER_API_KEY"] = " "

from crewai import Agent, Task, Crew
from crewai_tools import SerperDevTool, ScrapeWebsiteTool
from langchain_groq import ChatGroq
import arxiv

search_tool = SerperDevTool()
scrape_tool = ScrapeWebsiteTool()

llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0.2,
    max_tokens=600
)

literature_miner = Agent(
    role="Literature Miner",
    goal=(
        "Discover recent and influential research papers using arXiv, "
        "Google search results, and scholarly abstracts."
    ),
    backstory="Expert in academic search and systematic literature review.",
    tools=[search_tool, scrape_tool],
    llm=llm,
    verbose=True
)

methodology_analyzer = Agent(
    role="Methodology Analyzer",
    goal=(
        "Analyze and compare methodologies across research papers, "
        "focusing on models, datasets, and evaluation strategies."
    ),
    backstory="Experienced research scientist skilled in method comparison.",
    llm=llm,
    verbose=True
)

trend_synthesizer = Agent(
    role="Trend Synthesizer",
    goal=(
        "Identify emerging trends, dominant techniques, and evolving "
        "research directions from the literature."
    ),
    backstory="Specialist in scientific trend analysis.",
    llm=llm,
    verbose=True
)

research_gap_agent = Agent(
    role="Research Gap Agent",
    goal=(
        "Identify under-explored research gaps and propose concrete "
        "experiments or benchmarks."
    ),
    backstory="Focused on uncovering novel research opportunities.",
    llm=llm,
    verbose=True
)

task_1 = Task(
    description=(
        "Search for recent (last 3–5 years) research papers on the topic: {topic}. "
        "Summarize key contributions and datasets used."
    ),
    expected_output=(
        "A structured summary of recent research papers including titles, "
        "main contributions, datasets used, and publication year."
    ),
    agent=literature_miner
)

task_2 = Task(
    description=(
        "Compare methodologies across the collected papers, focusing on "
        "architectures, training strategies, and evaluation metrics."
    ),
    expected_output=(
        "A comparative analysis highlighting similarities, differences, "
        "strengths, and weaknesses of the methodologies."
    ),
    agent=methodology_analyzer
)

task_3 = Task(
    description=(
        "Identify emerging trends, frequently used techniques, and "
        "under-explored directions in the literature."
    ),
    expected_output=(
        "A synthesized list of emerging research trends and under-explored "
        "areas supported by evidence from the literature."
    ),
    agent=trend_synthesizer
)

task_4 = Task(
    description=(
        "Propose clear research gaps and suggest potential experiments "
        "or evaluation setups."
    ),
    expected_output=(
        "A list of clearly articulated research gaps along with suggested "
        "experiments or benchmarks to address them."
    ),
    agent=research_gap_agent
)

research_crew = Crew(
    agents=[
        literature_miner,
        methodology_analyzer,
        trend_synthesizer,
        research_gap_agent
    ],
    tasks=[
        task_1,
        task_2,
        task_3,
        task_4
    ],
    verbose=True
)

result = research_crew.kickoff(
    inputs={"topic": "Large Language Models for Code Generation"}
)

from IPython.display import Markdown
Markdown(result)